### ISSUE TITLE
Vasarnamių paieška pagal kriterijus

### ISSUE THREAD

**Issue by lawrence-laz** [karolis1994/PSK#42]

**Comment by lawrence-laz** [comment]
Privalomi paieškos kriterijai:
- Vietų skaičius
- Vasarnamio užimtumas/laisvumas pasirinktu laikotarpiu

**Comment by lawrence-laz** [comment]
Vietų skaičius atributas pridėtas (#54)

**Comment by Shankrie** [comment]
Done
