### ISSUE TITLE
Papildomų paslaugų užsakymas ir apmokėjimas atostogų metu

### ISSUE THREAD

**Issue by lawrence-laz** [karolis1994/PSK#60]
Užsakovas:

> Papildomos paslaugos yra užsakomos konkrečiai dienai/valandai. Jos gali būti užsakytos rezervavimo metu, arba atostogų metu.
> Pvz. rytoj lyja lietus, tai užsakom pirtį / ryt šviečia saulė, tai užsakom jodinėjimą žirgais.

**Comment by Shankrie** [comment]
Done 3eb0e7d
