### ISSUE TITLE
Pirmą kartą jungiantis prie Facebook turi būti sukuriamas įrašas Principals lentoj

### ISSUE THREAD

**Issue by lawrence-laz** [karolis1994/PSK#71]
Facebook paskyra susiejama su Principals per Facebook user id.

**Comment by karolis1994** [comment]
Dar reikėtų priskirti vartotojui facebook'o ID, jeigu vartotojas buvo užsiregistravęs paprastu būdu. Ir jeigu paskyra yra isDeleted = true reikėtų užsetint true.

**Comment by lawrence-laz** [comment]
O kaip atpažint, kad vartotojas užsiregistravęs paprastu būdu? Pagal email?

**Comment by karolis1994** [comment]
Taip, manau pagal email.
Dar pirmam komentare prie isDeleted parašiau, kad reikia priskirt true, susimaišiau, ten turėtų būti false ( kad per naujo aktyvuot ištrintą paskyrą ).
