### ISSUE TITLE
[Papildomų paslaugų rezervavimas] Defaultinė data toli ateity

### ISSUE THREAD

**Issue by lawrence-laz** [karolis1994/PSK#77]
![image](https://cloud.githubusercontent.com/assets/8823448/15585139/910b32ae-2386-11e6-8fa3-6db83b6ed7c6.png)

**Comment by lawrence-laz** [comment]
Tik paspaudus pasirinkti datą, kažkodėl atidaro 2021 metus.

**Comment by Shankrie** [comment]
Šitą bug'ą lygtais jau sutaisiau, hmmm gal dar nesupushinau. Nors apskritai tai aš šito task'o dar nepabaigiau tai ir neturėtų dar šitas feature'as veikt

**Comment by lawrence-laz** [comment]
Ok

**Comment by Shankrie** [comment]
Supushinau, turėtų veikt 3eb0e7d
